nginx:
    restart: always
    image: nginx:alpine
    ports:
        - "8080:80"
    volumes:
        # nginx
        - ./nginx:/etc/nginx

        # websites
        - ./default:/usr/share/nginx/html
        - ./damienrubio/dist/damienrubio:/usr/share/nginx/html/damienrubio
        - ./skrib:/usr/share/nginx/html/skrib

        #logs
        - ./logs:/var/log/nginx
    links:
        - php

php:
    restart: always
    image: php:7-fpm-alpine
    volumes:
        # websites
        - ./default:/usr/share/nginx/html
        - ./damienrubio/dist/damienrubio:/usr/share/nginx/html/damienrubio
        - ./skrib:/usr/share/nginx/html/skrib
