name: Web Resume CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: chmod +x resume/build.sh && ./resume/build.sh
  gcloud-deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy to gcloud
      uses: exelban/gcloud@263.0.0
      env:
        PROJECT_ID: web-resume-254010
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: app deploy resume/gcp